/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ExamplesGlobalStoreLazyImport = createFileRoute(
  '/examples/global-store',
)()
const ExamplesContextStoreLazyImport = createFileRoute(
  '/examples/context-store',
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExamplesGlobalStoreLazyRoute = ExamplesGlobalStoreLazyImport.update({
  id: '/examples/global-store',
  path: '/examples/global-store',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/examples/global-store.lazy').then((d) => d.Route),
)

const ExamplesContextStoreLazyRoute = ExamplesContextStoreLazyImport.update({
  id: '/examples/context-store',
  path: '/examples/context-store',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/examples/context-store.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/examples/context-store': {
      id: '/examples/context-store'
      path: '/examples/context-store'
      fullPath: '/examples/context-store'
      preLoaderRoute: typeof ExamplesContextStoreLazyImport
      parentRoute: typeof rootRoute
    }
    '/examples/global-store': {
      id: '/examples/global-store'
      path: '/examples/global-store'
      fullPath: '/examples/global-store'
      preLoaderRoute: typeof ExamplesGlobalStoreLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/context-store': typeof ExamplesContextStoreLazyRoute
  '/examples/global-store': typeof ExamplesGlobalStoreLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/context-store': typeof ExamplesContextStoreLazyRoute
  '/examples/global-store': typeof ExamplesGlobalStoreLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/examples/context-store': typeof ExamplesContextStoreLazyRoute
  '/examples/global-store': typeof ExamplesGlobalStoreLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples/context-store' | '/examples/global-store'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/context-store' | '/examples/global-store'
  id: '__root__' | '/' | '/examples/context-store' | '/examples/global-store'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesContextStoreLazyRoute: typeof ExamplesContextStoreLazyRoute
  ExamplesGlobalStoreLazyRoute: typeof ExamplesGlobalStoreLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesContextStoreLazyRoute: ExamplesContextStoreLazyRoute,
  ExamplesGlobalStoreLazyRoute: ExamplesGlobalStoreLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/examples/context-store",
        "/examples/global-store"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/examples/context-store": {
      "filePath": "examples/context-store.lazy.tsx"
    },
    "/examples/global-store": {
      "filePath": "examples/global-store.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
